version: '3.8'

services:
  app:
    build: ./node
    container_name: node_app
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8010:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
